In [1]:
import numpy as np

b = np.array([(1., 0., 0.), (0., 1., 2.)])
b

In [2]:
b.shape

(2, 3)

In [3]:
b.ndim

2

In [4]:
b.size

6

In [5]:
s=np.ones( (2,3,4), dtype=np.int16 )
s

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [6]:
s.ndim

3

In [7]:
# The function empty creates an array whose initial content
# is random and depends on the state of the memory.
# By default, the dtype of the created array is float64.

np.empty( (2,3) )

array([[9.34602321e-307, 2.11392033e-307, 1.60216183e-306],
       [7.56602523e-307, 1.11258446e-306, 6.23059726e-307]])

In [8]:
# To create sequences of numbers, NumPy provides
# the arange function which is analogous to 
# the Python built-in range, but returns an array.

np.arange( 10, 50, 5 )

array([10, 15, 20, 25, 30, 35, 40, 45])

In [9]:
# the linspace function receives as an argument
# the number of elements that we want, instead of the step:

from numpy import pi
np.linspace( 0, 2, 9 ) # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [10]:
# Arithmetic operators on arrays apply elementwise. 
# A new array is created and filled with the result.

a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [11]:
c = a-b
c

array([20, 29, 38, 47])

In [12]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [13]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [14]:
# The matrix product can be performed using the @ operator
# (in python >=3.5) or the dot function or method:

A = np.array( [[1,1],
               [0,1]] )
B = np.array( [[2,0],
               [3,4]] )
A * B                       # elementwise product
# array([[2, 0],
#        [0, 4]])

A @ B                       # matrix product
# array([[5, 4],
#        [3, 4]])

A.dot(B)                    # matrix product
# array([[5, 4],
#        [3, 4]])

array([[5, 4],
       [3, 4]])

In [15]:
# Many unary operations, such as computing the sum
# of all the elements in the array, are implemented
# as methods of the ndarray class.

rg = np.random.default_rng(1)     # create instance of default random number generator
a = rg.random((2,3))
a

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [16]:
a.sum()

3.290252281866131

In [17]:
a.min()

0.14415961271963373

In [18]:
a.max()

0.9504636963259353

In [19]:
# By default, these operations apply to the array as though
# it were a list of numbers, regardless of its shape.
# However, by specifying the axis parameter you can apply
# an operation along the specified axis of an array:

b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
b.sum(axis=0)     # sum of each column

array([12, 15, 18, 21])

In [21]:
b.min(axis=1)    # min of each row

array([0, 4, 8])

In [22]:
b.cumsum(axis=1)   # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [23]:
# One-dimensional arrays can be indexed, sliced 
# and iterated over, much like lists and other
# Python sequences

a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [24]:
a[3]

27

In [25]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [26]:
# from start to position 6, exclusive, set every 2nd element to 1000
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [27]:
a[::-1]  # reversed a

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)